#!/bin/sh
grep "^alias" ~/.bashrc > /dev/null
if [ "$?" -eq 1 ]
then

  cat >> ~/.bashrc << EOF
alias be='bundle exec'
alias bi='bundle install --path vendor --without system_tests development'
alias updatemaster='git checkout master && git fetch origin --prune --tags && git pull origin master'
alias updateprod='git checkout production && git fetch origin --prune --tags && git pull origin production'

# Get to the top of a git tree
cdp () {

  TEMP_PWD=`pwd`
  while ! [ -d .git ]; do
  cd ..
  done
  OLDPWD=$TEMP_PWD

}

# Check out a Pull request from github
function pr() {
  id=$1
  if [ -z $id ]; then
      echo "Need Pull request number as argument"
      return 1
  fi
  git fetch origin pull/${id}/head:pr_${id}
  git checkout pr_${id}
}
EOF

fi
