#!/bin/sh
cat > ~/.vimrc << EOF
" This file is managed by 'rnelson0-bash'
" All comments PRECEDE the stanza they refer to

" Enable mouse control
set mouse=a
" Unhighlight current search results
map ,/ :silent noh<CR>

" Show non-ASCII characters (like emoji) with a red highlight
highlight nonascii guibg=Red ctermbg=1 term=standout
au BufReadPost * syntax match nonascii "[^\u0000-\u007F]"

EOF
